/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export function __wbg_playermetadata_free(a: number, b: number): void;
export function __wbg_get_playermetadata_PlayerID(a: number): number;
export function __wbg_set_playermetadata_PlayerID(a: number, b: number): void;
export function __wbg_get_playermetadata_APM(a: number): number;
export function __wbg_set_playermetadata_APM(a: number, b: number): void;
export function __wbg_metadata_free(a: number, b: number): void;
export function __wbg_get_metadata_Title(a: number): Array;
export function __wbg_set_metadata_Title(a: number, b: number, c: number): void;
export function __wbg_get_metadata_GameVersion(a: number): Array;
export function __wbg_set_metadata_GameVersion(a: number, b: number, c: number): void;
export function __wbg_get_metadata_DataBuild(a: number): Array;
export function __wbg_set_metadata_DataBuild(a: number, b: number, c: number): void;
export function __wbg_get_metadata_DataVersion(a: number): Array;
export function __wbg_set_metadata_DataVersion(a: number, b: number, c: number): void;
export function __wbg_get_metadata_BaseBuild(a: number): Array;
export function __wbg_set_metadata_BaseBuild(a: number, b: number, c: number): void;
export function __wbg_get_metadata_Duration(a: number): number;
export function __wbg_set_metadata_Duration(a: number, b: number): void;
export function __wbg_get_metadata_Players(a: number): Array;
export function __wbg_set_metadata_Players(a: number, b: number, c: number): void;
export function __wbg_replay_free(a: number, b: number): void;
export function __wbg_get_replay_parsed(a: number): number;
export function __wbg_set_replay_parsed(a: number, b: number): void;
export function replay_new(a: number, b: number, c: number, d: number): number;
export function test(): Array;
export function __wbg_set_playermetadata_Result(a: number, b: number, c: number): void;
export function __wbg_set_playermetadata_SelectedRace(a: number, b: number, c: number): void;
export function __wbg_set_playermetadata_AssignedRace(a: number, b: number, c: number): void;
export function __wbg_set_replay_file_path(a: number, b: number, c: number): void;
export function __wbg_set_replay_content_hash(a: number, b: number, c: number): void;
export function __wbg_get_playermetadata_Result(a: number): Array;
export function __wbg_get_playermetadata_SelectedRace(a: number): Array;
export function __wbg_get_playermetadata_AssignedRace(a: number): Array;
export function __wbg_get_replay_file_path(a: number): Array;
export function __wbg_get_replay_content_hash(a: number): Array;
export function __wbindgen_malloc(a: number, b: number): number;
export function __wbindgen_realloc(a: number, b: number, c: number, d: number): number;
export const __wbindgen_export_2: WebAssembly.Table;
export function __wbindgen_free(a: number, b: number, c: number): void;
export function __externref_drop_slice(a: number, b: number): void;
export function __externref_table_alloc(): number;
export function __wbindgen_exn_store(a: number): void;
export function __wbindgen_start(): void;
